// @ts-nocheck
'use client';
import type { Metadata } from 'next';
import './globals.css';
import '@rainbow-me/rainbowkit/styles.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { RainbowKitProvider } from '@rainbow-me/rainbowkit';
import { WagmiProvider } from 'wagmi';
import { QueryClientProvider } from '@tanstack/react-query';
import { queryClient } from '../lib/react-query';
import { wagmiConfig } from '../config/wagmi';
import { ToastContainer } from 'react-toastify';


const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className="font-sans antialiased overflow-x-hidden text-sm"
            >
                <div className="relative bg-yellow-700">
                    <WagmiProvider config={wagmiConfig}>
                        <QueryClientProvider client={queryClient}>
                            <ToastContainer />
                                <RainbowKitProvider>
                                    <Header />
                                    <div className="min-h-screen max-w-6xl mx-auto space-y-8 px-5 py-14 lg:px-10">
                                        {children}
                                    </div>
                                    <Footer />
                                </RainbowKitProvider>
                        </QueryClientProvider>
                    </WagmiProvider>
                </div>
            </body>
        </html>
    );
}

